version: "3.9"

services:
  server: 
    container_name: rmi-server-maven
    image: rmi-server-maven
    build:
      context: server/.
      dockerfile: Dockerfile-maven
    volumes:
      - servervol:/serverdata
    networks:
      - rmi
  client:
    container_name: rmi-client-maven
    image: rmi-client-maven
    build:
      context: client/.
      dockerfile: Dockerfile-maven
    depends_on:
      - server
    volumes:
      - clientvol:/clientdata
    networks:
      - rmi
    links:
      - "server:server"
networks:
  rmi:
    driver: bridge
volumes:
  clientvol:
    name: clientvol
  servervol:
    name: servervol